title: Datasets for Schoch et al 2018
description: Adolescent cannabinoid exposure effects on natural reward seeking and learning in rats. Schoch, H, Huerta, MY, Ruiz, CM, Farrell, MR, Jung, KM, Huang, JJ, Campbell, RR, Piomelli, D & Mahler, SV. (2018).

publisher_text: Link to paper
publisher_url: https://cpb-us-e2.wpmucdn.com/faculty.sites.uci.edu/dist/9/365/files/2017/11/Schoch-et-al-Psychopharm-2017.pdf

license_text: 
license_url: 

frequency: 

certificate_embed: 
