title: Adolescent cannabinoid exposure effects on natural reward seeking and learning in rats
description: An example dataset. This text could be quite long.

publisher_text: Psychopharmacology
publisher_url: https://cpb-us-e2.wpmucdn.com/faculty.sites.uci.edu/dist/9/365/files/2017/11/Schoch-et-al-Psychopharm-2017.pdf

license_text: 
license_url: 

frequency: 

certificate_embed: 
